- uses: Platane/snk@v2
    github_user_name: ${{ sala7khaled }}
    outputs: |
      assets/github-snake.svg
      assets/github-snake-dark.svg?palette=github-dark
      assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
